server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/Homework
    username: postgres
    password: 14420605
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: create-drop
