server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/staging
    username: postgres
    password: 14420605
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration,classpath:staging/db/migration